"LR": 0.001
"NUM_ENVS": 64
"NUM_STEPS": 128
"BUFFER_SIZE": 1
"LOG_TERM": 8
"TOTAL_TIMESTEPS": 1e7
"HIDDEN_SIZE": 128
"NUM_LAYERS" : 2
"UPDATE_EPOCHS": 5
"NUM_MINIBATCHES": 1
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 1.0
"ACTIVATION": "relu"
"SEED": 0
"ENV_NAME": "halfcheetah_6x1" 
"ENV_KWARGS": {}
"ANNEAL_LR": True
"DEVICE": 0
"DISABLE_JIT": False
"VALUE_NORM": False
"ADVANTAGE": gpae
"LAYER_NORM": True
"NORM_INPUT": True
"CORRECTION": "dt"
"DT_ETA": 1.05


# WandB Params
"WANDB_MODE": "online"
"ENTITY": ""
"PROJECT": ""